// "use client:"
import Link from "next/link";
import "./globals.css";
import {Control} from './Control';


export const metadata = {
  title: "만들어보자",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {


    //여기서 데이터를 받아올 때 생성된 캐시를 삭제해야 글 목록이 업데이트 된다.
    //Next.js 공식문서에서는 "Revaidating"항목으로 해결할 수 있다.
    const resp = await fetch('http://localhost:9999/topics', {cache: 'no-store'});
    /*방법1.
       const resp = await fetch('http://localhost:9999/topics', {next: {revalidate: 0}});
       fetch의 변수에 {next: {revalidate: 0}} : 0초동안만 캐시를 유지한다.*/

    /*방법2. Dynamic Data Fetching
      fetch의 변수에 {cache: 'no-store'}: 캐시를 저장하지 않는다.
    */ 
    //fetch명령어를 사용하면 .next에 이러한 정보들(캐시)이 저장된다. 이떄문에 저장 후 목록이 나타지않는다.
    //그래서 이를 삭제해야함
    const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB from layout.js</Link></h1>
        <ol>
          {topics.map((topic) => {
               return <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>
                    {topic.title}
                  </Link>
                </li> 
            })}
        </ol>
        {children}

        <Control/>
      </body>
    </html>
  );
}
